url: "https://florian-s.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Florian Schuttkowski"

include: ['_pages']

permalink: /:year/:title:output_ext
